apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordon.fullname" . }}-secrets
  labels:
    {{- include "cordon.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Dashboard / session auth
  CORDON_DASHBOARD_KEY: {{ .Values.auth.dashboardKey | quote }}
  CORDON_SESSION_SECRET: {{ .Values.auth.sessionSecret | quote }}

  # Database
  DATABASE_URL: {{ .Values.database.url | quote }}

  {{- if .Values.auth.oidc.enabled }}
  # OIDC
  CORDON_OIDC_ISSUER:        {{ .Values.auth.oidc.issuer | quote }}
  CORDON_OIDC_CLIENT_ID:     {{ .Values.auth.oidc.clientId | quote }}
  CORDON_OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | quote }}
  CORDON_OIDC_REDIRECT_URI:  {{ .Values.auth.oidc.redirectUri | quote }}
  CORDON_OIDC_SCOPES:        {{ .Values.auth.oidc.scopes | quote }}
  {{- end }}
